replicaCount: 2

image:
  repository: your-dockerhub-username/java-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  profile: prod
  datasource:
    url: jdbc:postgresql://db-service:5432/mydb
    username: myuser
    password: mypass

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: java-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []  # Add TLS config here if needed
