apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "java-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "java-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "java-app.name" . }}
    spec:
      containers:
        - name: java-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.profile }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.datasource.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.datasource.password }}
