project_id                = "peerless-robot-426711-j3"
region                    = "us-east1"
app_name                  = "gcp-sentiment-api"
image                     = "docker.io/rajeshkrvd/gcp-sentiment-api:1.2.3"
cloudrun_invoker          = "allUsers"