project_id     = "peerless-robot-426711-j3"
region         = "us-east1"
app_name       = "gcp-sentiment-api"
image          = "docker.io/rajeshkrvd/gcp-sentiment-api:latest"
cicd_sa_email  = "terraform-cicd@peerless-robot-426711-j3.iam.gserviceaccount.com"