project_id     = "peerless-robot-426711-j3"
region         = "us-east1"
service_name   = "gcp-sentiment-api"
image_name     = "docker.io/rajesh.krvd/gcp-sentiment-api"
image_tag      = "1.0.1"
cicd_sa_email  = "terraform-cicd@peerless-robot-426711-j3.iam.gserviceaccount.com"
