variable "project_id" {}
variable "region" {}
variable "app_name" {}
variable "image" {}
variable "cicd_sa_email" {}
variable "deployer_permissions" {}
variable "sa_roles" {}
variable "bucket_name" {}
variable "invoker" {}
variable "invoker_role" {}
variable "invoker_permissions" {}
variable "storage_roles" {}