apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web
          image: docker.io/rajeshkrvd/web-app:fd100766fb3939e7abe3ff3c160181f0c62c802a
          ports:
            - containerPort: 80