apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
        - name: web
          image: 
          ports:
            - containerPort: 80