apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
    version: blue  # Initial routing to blue
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
