name: Argo CD

on:
  push:
    paths:
      - 'argocd/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}
          docker build -t $IMAGE_TAG ./argocd/app
          docker push $IMAGE_TAG

      - name: Update deployment image
        run: |
          sed -i "s|image:.*|image: $IMAGE_TAG|" ./devops/argocd/k8s/deployment.yaml

      - name: Commit and push updated YAML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./argocd/k8s/deployment.yaml
          git commit -m "Update image to $IMAGE_TAG"
          git push