name: flask-app-cicd

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image And Push
        run: |
          
          IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/flask-app:latest
          docker build -t $IMAGE_TAG ./flask-app
          docker push $IMAGE_TAG

      - name: Update manifest with new image tag
        run: |
          sed -i "s|image: .*$|image: $IMAGE_NAME:$IMAGE_TAG|" flask-app/deployment.yaml

      - name: Commit and push changes
        env:
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          cd flask-app
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to $IMAGE_TAG"
          git push origin HEAD:main