name: Full GCP Cleanup

on:
#  schedule:
#    - cron: '30 6 * * *'  # 12:00 PM IST daily
#    - cron: '*/10 * * * *'  # For every 10mins
  workflow_dispatch:  # Manual trigger

jobs:
  full-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Delete all Cloud Run services
        run: |
          for service in $(gcloud run services list --format="value(metadata.name)" --region=us-east1); do
            gcloud run services delete "$service" --region=us-east1 --quiet || echo "$service not found"
          done

      - name: Delete all Docker images in Artifact Registry
        run: |
          for repo in $(gcloud artifacts repositories list --location=us-east1 --format="value(name)"); do
            gcloud artifacts docker images list $repo --format="value(name)" | while read image; do
              gcloud artifacts docker images delete "$image" --delete-tags --quiet || echo "$image not found"
            done
            gcloud artifacts repositories delete $repo --location=us-east1 --quiet || echo "$repo already deleted"
          done

      - name: Delete all GCS buckets (force)
        run: |
          for bucket in $(gsutil ls); do
            gsutil -m rm -r "$bucket" || echo "$bucket not found"
          done

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6 # or any version you prefer

      - name: Destroy Terraform - GCP Docker Java App
        working-directory: ./gcp-docker-java-app/infra
        run: terraform init && terraform destroy -auto-approve

      - name: Destroy Terraform - GCP Sentiment API
        working-directory: ./gcp-sentiment-api/iac
        continue-on-error: true
        run: terraform init && terraform destroy -auto-approve

      - name: Destroy Terraform - GCP Static Website
        working-directory: ./gcp-static-website/infra
        continue-on-error: true
        run: terraform init && terraform destroy -auto-approve