name: gcp-docker-java-app-cicd

on:
  push:
    branches: [ main ]
    paths:
      - 'gcp-docker-java-app/**'

env:
  APP_NAME: gcp-docker-java-app
  REGION: us-east1
  IMAGE_URL: docker.io/rajeshkrvd/gcp-docker-java-app:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Package JAR with Maven
        working-directory: ./gcp-docker-java-app
        run: mvn clean package

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Docker login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t $IMAGE_URL ./gcp-docker-java-app
          docker push $IMAGE_URL

      - name: 🔄 Delete existing Cloud Run service (if any)
        run: |
          gcloud run services delete $APP_NAME \
            --region=$REGION \
            --quiet || echo "No existing service to delete"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: gcp-docker-java-app/infra
        run: terraform init

      - name: Terraform Apply
        working-directory: gcp-docker-java-app/infra
        run: terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="region=${{ env.REGION }}" -var="app_name=${{ env.APP_NAME }}" -var="image=${{ env.IMAGE_URL }}"
