name: flask-app-cicd

on:
  push:
    branches:
      - main
    paths:
      - 'flask-app/**'

permissions:
  contents: write

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app
  IMAGE_TAG: v7
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image And Push
        run: |

          docker build -t $IMAGE_NAME:$IMAGE_TAG ./flask-app
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update image tag in Kubernetes manifest
        run: |
          sed -i "s|image: .*|image: $IMAGE_NAME:$IMAGE_TAG|" flask-app/k8s/deployment.yaml
          echo "Updated deployment.yaml to use $IMAGE_NAME:$IMAGE_TAG"
      - name: Print deployment.yaml after sed
        run: cat flask-app/k8s/deployment.yaml
      - name: Commit and push changes
        env:
          MY_GITHUB_PAT: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          cd flask-app
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          
          git add k8s/deployment.yaml
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "Update image to $IMAGE_NAME:$IMAGE_TAG"
            git push origin HEAD:main
          fi